language: python
python:
 - "3.9"
 - "nightly"
before_install:
 - "sudo apt-get install build-essential python3-dev"
install:
 - "pip install pipenv"
 - "pipenv install"
before_script: pip freeze
script: pytest tests/